version: '3'
services:
  app:
    container_name: py-app
    image: py-app:latest
    build: ./docker
    volumes:
      - ./:/opt/app
    command: "tail -f /dev/null"
    environment:
      - ENV=dev
