routes:
  path: config/routes.yml

api:
  url: 'https://hostname/api'
  access_key: ''
  access_token: ''

di:
  app.lib.auth.Auth:
    path: app.lib.auth
    module: Auth
    args: []
  i18n.locale.Locale:
    path: i18n.locale
    module: Locale
    args:
      - jp
