env: dev

routes:
  path: config/routes.yml

api:
  url: 'https://hostname/api'
  access_key: ''
  access_token: ''

di:
  logger:
    path: log.driver.filelogger
    module: FileLogger
    args:
      - DEBUG
      - /logs/app.log

  authorize:
    path: app.lib.auth
    module: authorize
    args: []

  locale:
    path: i18n.locale
    module: Locale
    args:
      - jp
