routes:
  path: config/routes.yml

api:
  url: 'https://hostname/api'
  access_key: ''
  access_token: ''

di:
  auth:
    module: app.lib.auth
    class: Auth
  locale:
    module: i18n.locale
    class: Locale
    args:
      - jp
